
# use_frameworks!

require_relative '../../orbitRNApp/node_modules/react-native/scripts/react_native_pods'
# require_relative '../../orbitRNApp/node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

target 'OrbitCoordinator' do
  pod 'OrbitCoordinator', :path => '../'
  pod 'MyTelkomselSuperappFrameworkIntegration', :path => '../../../mytelkomsel-superapp-framework-integration-ios'
 pod 'MyTelkomselSuperappFramework', :path => '../../../mytelkomsel-superapp-framework-ios'

flags = get_default_flags()

use_react_native!(
    :path => '../../orbitRNApp/node_modules/react-native',
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true,
    :fabric_enabled => true,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end

end
